### ISSUE TITLE
Input norm module can't handle '?????' as reported concentration

### ISSUE THREAD

**Issue by RodolfoSalido** [tanaes/metagenomics_pooling_notebook#1]
The automated quant procedure we use will occasionally output '?????' as the reported concentration. This means that the sample was outside the detection window. The script should be able to handle '????' and treat them as '0'. 
<img width="1102" alt="screen shot 2017-09-05 at 9 18 58 am" src="https://user-images.githubusercontent.com/13193891/30071367-4cf976a2-921b-11e7-95ba-105afbd0ea79.png">

**Comment by tanaes** [comment]
Can you paste me an example section of a file here so I can add to test? Thanks!

**Comment by RodolfoSalido** [comment]
[2017-08-17-Manary_1-4_faulty.txt](https://github.com/tanaes/metagenomics_pooling_notebook/files/1279021/2017-08-17-Manary_1-4_faulty.txt)

**Comment by tanaes** [comment]
Fixed this in commit 928516acbb9b57f571e5b92152f16d51b3e9364f
