### ISSUE TITLE
SampleSheet generation tab delimited bug

### ISSUE THREAD

**Issue by RodolfoSalido** [tanaes/metagenomics_pooling_notebook#10]
The column headers for [Data] aspect of the sample sheet is still tab delimited after specifying , as delimiter. 
<img width="1122" alt="screen shot 2017-09-14 at 11 44 11 am" src="https://user-images.githubusercontent.com/13193891/30447943-3e9a54cc-9942-11e7-940f-e8308dadb838.png">

[CF_1-2_samplesheet.xlsx](https://github.com/tanaes/metagenomics_pooling_notebook/files/1304137/CF_1-2_samplesheet.xlsx)

**Comment by tanaes** [comment]
derp. fixing.

**Comment by tanaes** [comment]
Should be fixed in b1e6134af5edc6182a8e903a2f77ddfe20856762
