### ISSUE TITLE
Max_vol_per_well function in pooling pick list can't handle nan values

### ISSUE THREAD

**Issue by RodolfoSalido** [tanaes/metagenomics_pooling_notebook#14]
The max_vol_per_well function failed to cycle to the next well when exceeding max vol. After inspecting the transfer volumes, I have the belief that it's an error that was introduced by nan values being present in the pooling volumes. Nan values throw off the function. 
Attached is the faulty pooling pick list. 
[2017-11-22_FinRisk_5-8_81-83_lisas_normpool.txt](https://github.com/tanaes/metagenomics_pooling_notebook/files/1497272/2017-11-22_FinRisk_5-8_81-83_lisas_normpool.txt)

**Comment by tanaes** [comment]
Resolved in commit c779a73; wells with NaN now get pooled as '0.00'.
