### ISSUE TITLE
Support for Library Prep on 192 format. 

### ISSUE THREAD

**Issue by RodolfoSalido** [tanaes/metagenomics_pooling_notebook#2]
The notebook should support the option of making a 192 format normalized DNA plate given appropriate sample maps and quant data. 
I've attached Quant data and Sample maps for CF strains plates 1-2.

[192support.zip](https://github.com/tanaes/metagenomics_pooling_notebook/files/1278830/192support.zip)

The goal of adding 192 format support is to reformat samples into the first half of the destination plate regardless of where the source well of each samples is.

**Comment by tanaes** [comment]
Added this in commit d2fd4d0fffe3086c7b7eb9e742073426a77cf479

The solution here is to provide a function that takes our fully-interleaved plate format and converts each corresponding interleaved well code to one in a column-organized plate, where the odd columns in odd rows (plate 1) are put into the first 6 columns of a 384 plate, with odd rows corresponding to the first six columns and even rows corresponding to the latter six columns. 

This will also support arbitrary reassignment, as long as you can add a column to the dataframe with the corresponding well codes.
