### ISSUE TITLE
min_conc pooling value

### ISSUE THREAD

**Issue by RodolfoSalido** [tanaes/metagenomics_pooling_notebook#3]
Notebook should pool samples that don't meet min_conc at 100nL instead of 0nL.

**Comment by tanaes** [comment]
Addressed by commit 928516acbb9b57f571e5b92152f16d51b3e9364f

Currently the notebook includes all three options for visualization, but we can cut down to default if better for production.

**Comment by tanaes** [comment]
Need to check description on markdown well
